### ISSUE TITLE
package is invalid: 'CRX_PROOF_MISSING'.

### ISSUE THREAD

**Issue by shinas101** [FastForwardTeam/releases#14]
`package is invalid: 'CRX_PROOF_MISSING'.`
this  error while installing the .crx file 

I have made changes to registry.

os: windows
browser: chrome(latest)

**Comment by DavidH-2022** [comment]
You need to unpack (unzip) the `.crx` file you have downloaded, you can do that with software like 7-zip (https://7-zip.org/), or  rename the file extension from `.crx` to `.zip` and unzip using other software.

**Comment by shinas101** [comment]
i

> You need to unpack (unzip) the `.crx` file you have downloaded, you can do that with software like 7-zip (https://7-zip.org/), or rename the file extension from `.crx` to `.zip` and unzip using other software.

i did what you said and it installed successfully ( ❤️  thanks for that ) , but now it stuck on `[DOWNLOADING BYPASS DEFINITIONS...` on extension page .

Any idea what  error it is ?

**Comment by mreduar** [comment]
> Did you get any solution?

**Comment by shinas101** [comment]
> 

nope

**Comment by mreduar** [comment]
> i did what you said and it installed successfully ( ❤️ thanks for that ) , but now it stuck on `DOWNLOADING BYPASS DEFINITIONS...` on extension page .

After that you have to delete a file that indicates the welcome message and that's it.

**Comment by princessmortix** [comment]
See https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md
