### ISSUE TITLE
Package is invalid: 'CRX_HEADER_INVALID'

### ISSUE THREAD

**Issue by RoobyRoobyRoo** [FastForwardTeam/releases#15]
I keep getting the message `Package is invalid: 'CRX_HEADER_INVALID'`  when I drag the .crx into chrome://extensions.

I added the registry and developer mode is checked
To clarify, this was happening before instructions to install the registry file were added **and** afterward.

OS: Windows
Browser: Chrome (latest)

**Comment by RoobyRoobyRoo** [comment]
To clarify, this was happening before instructions to install the registry file were added **and** afterward.

**Comment by alexx-ftw** [comment]
same here

**Comment by a10kiloham** [comment]
Downloading the file in rel/FastForward0.0.8.crx manually then dragging it into the extensions page works.

**Comment by RoobyRoobyRoo** [comment]
If you mean https://github.com/FastForwardTeam/releases/blob/main/rels/FastForward0.0.8.crx
That doesn't work either.

**Comment by a10kiloham** [comment]
Hm, with the registry changes and restarting chrome after that just worked for me (and was the only way) in the newest Chrome on Windows this AM.
Alternately, follow the directions to download the CRX to your hard drive, rename it .zip, open it with 7Zip or whatever, then drag the contents to a new folder. then drag that folder into your extensions tab.
