### ISSUE TITLE
Package is invalid: 'CRX_REQUIRED_PROOF_MISSING'

### ISSUE THREAD

**Issue by nesper8** [FastForwardTeam/releases#16]
OS: Linux (Nobara 36)
Browser Package: `chromium-freeworld`

**Comment by a10kiloham** [comment]
Same here Win 11/Chrome 107.0.5304.107
Registry changes confirmed and browser restarted. Other CRX plugins load normally still.

Downloading the file in rel/FastForward0.0.8.crx manually then dragging it into the extensions page works however

**Comment by princessmortix** [comment]
See https://github.com/FastForwardTeam/FastForward/blob/main/INSTALLING.md
