### ISSUE TITLE
Fast Forward not installing in Kiwi Browser Android 12

### ISSUE THREAD

**Issue by BarehSolok** [FastForwardTeam/releases#3]
### Body

Fast Forward does not install in Kiwi Browser (Android)
using Android 12

### Version

0.0.0

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NotAProton** [comment]
you followed https://github.com/FastForwardTeam/releases#kiwi-android , right?

**Comment by BarehSolok** [comment]
> 
> 
> you followed https://github.com/FastForwardTeam/releases#kiwi-android , right?

yes i have followed the instruction, now that i have downgraded to android 11, it's still not installing

**Comment by NotAProton** [comment]
It works on my phone (android 11), can you try again with the latest version?

**Comment by BarehSolok** [comment]
> It works on my phone (android 11), can you try again with the latest version?

i haven't tried the zip file, but the one in chrome extension store worked, thanks
